<a href="https://colab.research.google.com/github/onsoon829/dataproject/blob/master/101_%EC%A0%9C%EC%96%B4%EB%AC%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 비교연산자
 - <       >       <=      >=      ==      !=(기본적으로 사용되는 연산자)
 - 결과는 논리값 : True or False

In [ ]:
print(3 < 2)
print(3 > 2)
print(3 == 2)
print(3 != 2)

False
True
False
True


##논리연산자
 - &       |       ^

In [ ]:
# print(True and True)
# print(True or True)
# print(not True)


# existance
 - python에서 조건은 존재론(existance)적이다.=>truthy,falsey

In [ ]:
#0은 숫자가 없는 것과 같음 -> falsey
a = 0.0
if a:
  print('Yes')
else :
  print('No')

No


In [ ]:
#None은 숫자가 없는 것과 같음-> falsey
a = None
if a:
  print('Yes')
else:
  print('No')

No


In [ ]:
#비어 있는 dict은 없는 것과 같음 ->falsey
a = {}
if a:
  print('Yes')
else:
   print('No')

No


In [ ]:
a = int()
b = float()
c =list()
d = tuple()
e = str()
f = set()
g = frozenset()

if a:
  print('Yes')
else:
  print('No')

No


In [ ]:
3<2 or 4<5

True

In [ ]:
#and 연산자 쓸 때 c나 java는 양쪽이 꼭 같아야 한다.
#and는 앞이 True이면 뒤에 값을 반환한다.
3 and 4

4

In [ ]:
#뒤에 놈이 값을 결정한다.but 앞놈이 false값일 경우 값은 false값이 출력된다.
3 and 0

0

In [ ]:
#and는 앞이 false이면 앞의 값을 반환한다.
#비어있는 문자열은 없는 것과 같음 -> flasey ex) '' and 3-> ''
'' and 3

''

In [ ]:
#앞이 True이면 앞의 값이 리턴된다.
1 or 4

1

In [ ]:
#앞이 false이면 뒤의 값을 리턴한다
'' or 4

4

#제어문(statement controller)
 - 문장의 흐름을 제어해 준다.
 - 조건문, 반복문
 - 조건문: if~else
 - 반복문: for~in, while
 - break, continue

```
if 조건식:
  수행할 문장
else:
수행할 문장
```

In [ ]:
a = 8
if a>5 :
  print('OK')
else:
    print('Fail')

OK


In [ ]:
a= 5
if a%2==0 :
  print('even')
else:
  print('odd')


odd


In [ ]:
name = '홍길동'
if name :
  print(name)

홍길동


In [ ]:
#if조건에 문장을 사용할 수 없다.
if a=4:
  print(a)

SyntaxError: ignored

In [ ]:
#80이상이면 '상', 60이상 80미만이면 '중', 60미만이면 '하'
a = 85
if a>=80:
  print('상')
#else+if->elif
elif a>=60:
  print('중')
else:
  print('하')

상


In [ ]:
a = 65
if a >= 80:
  print('상')
else:
  if a>=60:
    print('중')
  else:
    print('하')

중


In [ ]:
a = 85
if  a>=60 :
  if a >=80 :
    print('상')
  else:
    if a>=60:
      print('중')
else:
     print('하')

상


In [ ]:
member = True
grade = 'A' # 'S' 50, 'A' 30
point = 0

if member:
#pass
  if grade == 'S':
    point = 50
  else:
    point = 30
else:
  point = 0

print(point)

30


In [ ]:
age = int(input('나이:'))
gender = input('성별[남,여]:')

if gender=='남':
  if age >= 20 :
    print('성인 남성입니다.')
  else:
    print('청소년 남성입니다')
else:
  if age >=20 :
    print('성인 여성입니다')
  else:
    print('청소년 여성입니다')

나이:10
성별[남,여]:남
청소년 남성입니다


* 퀴즈
1. 놀이기구에 키가 140cm이상이고,
  나이가 8세 이상인 사람만 탑승한다고 가정합니다.
2. 먼저 키(height)와 나이(age)를 입력받으세요.
3. 조건문 if~else를 사용하여 2개의 조건이 모두 참일 경우
  "놀이기구에 탑승할 수 있습니다."를 출력하세요.
4. 위 조건이 거짓일 경우 "놀이기구에 탑승할 수 없습니다."
    를 출력하세요.
5. 조건식과는 별개로 "오늘 하루 즐거운 시간되세요!"
   를 출력하세요.
'''

In [ ]:
height = int(input('키:'))
age = int(input('나이:'))

if height >= 140 :
   if age >= 8 :
    print('놀이기구에 탑승할 수 있습니다')
   else:
    if height <=140 :
       if age <= 8 :
          print('놀이기구에 탑승할 수 없습니다.')



키:140
나이:5
놀이기구에 탑승할 수 없습니다.


In [ ]:
#선생님 답안
height = int(input('키:'))
age = int(input('나이:'))

if height>=140 and age >= 8 :
  print('놀이기구에 탑승할 수 있습니다')
else:
  print('놀이기구에 탑승할 수 없습니다')

print('오늘 하루 즐거운 시간 되세요')

키:145
나이:9
놀이기구에 탑승할 수 있습니다
오늘 하루 즐거운 시간 되세요




'''

In [ ]:
age = input('나이:')
point_card = input('소지 여부:')
count = input('본 횟수:')

if age >= 18:
  if point_card == True:
     if count == 5:
     print('티켓은 5000원입니다')


SyntaxError: ignored

In [ ]:
#선생님 답안
age = int(input('나이:'))
point_card = bool(input('포인트 소지여부:'))
count = int(input('영화 관람 티켓 갯수:'))

if age < 18:
  print('티켓을 판매할 수 없습니다')
elif age >=60 or (point_card==True and count==5):
  print('티켓은 5000원입니다')
else:
  print('티켓은 8000원입니다')

나이:15
포인트 소지여부:o
영화 관람 티켓 갯수:1
티켓을 판매할 수 없습니다


In [ ]:
#윤년 : 연도를 4로 나누어 떨어지고 100으로 나누어 떨어지거나
#              400으로 나누어 떨어지면 된다
year = int(input('year:'))
month = int(input('month:'))
end_day_31 = [1,3,5,7,8,10,12]
end_day_30 = [4,6,9,11]
day = 28
check = ''

if not(month >= 1 and month <=12) :
  print('월은 1부터 12까지만 입력해 주세요')
  sys.exit()#현재 시스템을 빠져나올 때 사용. 시스템 종료

#if month==4 or month==6 or month==9 or month==11 :
if month in end_day_30:
   day=30
else:
   day=31

if (year%4==0 and year%100!=0) or year%400==0 :
   check='윤년'
   if month==2:
     day = 29

else:
   check='평년'
   if month==2:
     day = 28


print('{}년도 {}월은 평년, 마지막일 {}일입니다'.format(year, month, day))


year:2013
month:11
2013년도 11월은 평년, 마지막일 30일입니다


##반복문 : while
반복문에서 else는 반복문이 완벽하게 끝났을 때 실행된다.
대부분의 프로그래밍 언어는 while과 for을 지원한다.
else
  -if-else
  -try-except-else-finally
  -while-else
```
while 조건식:
  수행할 문장
else:
  수행할 문장  
```


In [ ]:
#while문이 완벽하게 돌았으므로 end가 출력된다.
a = 10
while a > 5 :
  a -= 1 #a = a - 1
  print(a)
else:
  print('end')

9
8
7
6
5
end


In [ ]:
#while문을 강제적으로 빠져나왔기 때문에 else영역을 실행하지 않는다.
a = 10
while a > 5 :
  a -= 1 #a = a - 1
  print(a)
  if a==5:
    break #반복문을 강제적으로 빠져나올 때 사용한다.->반복문을 중단시킨다.
else:
  print('end')#else 생략 가능?

9
8
7
6
5


In [ ]:
# continue는 다음 루프(조건식)로 바로 넘어간다.
#반복문을 중단하지는 않으므로 else문이 실행된다.
a = 10
while a > 5 :
   a -= 1
   if a % 2 == 0 :
    continue
   print(a)
else:
  print('end')

9
7
5
end


In [ ]:
# 1부터 10까지 출력하는 프로그램
a = 1
while a <= 10 :
  print(a)
  a = a + 1 #a += 1
  #a++ : 파이썬에선 이런 형식 지원 안한다.

1
2
3
4
5
6
7
8
9
10


In [ ]:
# 1부터 10까지 출력하고 합계 구하는 프로그램 구현

a = 1
even = 0    #짝수
odd = 0     #홀수
while a <= 10 :
  if a % 2 == 1 :    #홀수인가?
     odd = odd + a   #odd += a
  else:
     even = even + a #even += a
  a = a + 1          #a += 1

print('짝수={}'.format(even))
print('홀수={}'.format(odd))

짝수=30
홀수=25


for문과 함께 사용되는 함수
 - for 변수 in range(시작번호, 마지막번호, 증감값):
       실행구문

   for 변수 in enumerate(sequence, start):
       실행구문

   for 변수 in zip(data1, data2,...):
       실행구문        

###range


In [ ]:
#range(end)
for i in range(5): # 0부터 5미만의 값이 1씩 증가해서 생성된다.
  print(i)

0
1
2
3
4


In [ ]:
#range(start,end)
for i in range(1, 5): #1부터 5미만의 값이 1씩 증가해서 생성된다.
  print(i)

1
2
3
4


In [ ]:
#range(start,end, step)
for i in range(1, 5, 2): #1부터 5미만의 값이 2씩 증가해서 생성된다.
  print(i)

1
3


#### enumerate 함수
 - enumerate()함수는 인덱스와 객체를 동시에 저장할 수 있는 특징을 가진 for문을 좀더 효율적으로 사용하기 위한 함수이다.
 - enumerate()함수는 순서자료형(list, tuple, str)을 입력으로 받아 인덱스를 포함하는 enumerate 객체를 리턴한다.
 - enumerate([순서자료형], [시작값=0])의 형식을 가지며 순서자료형은 반복자가 가능한 객체가 입력도고 시작값은 입력시 해당수 부터 증가하며, 생략했을 경우 기본값은 0 이다.

In [ ]:
for k in enumerate(['apple','python','microsoft']):
  print(k)

(0, 'apple')
(1, 'python')
(2, 'microsoft')


In [ ]:
for k,v in enumerate(['apple','python','microsoft']):
  print(k, v)

0 apple
1 python
2 microsoft


In [ ]:
for k,v in enumerate(['apple','python','microsoft'], 1):
  print(k, v)

1 apple
2 python
3 microsoft


In [ ]:

for k in enumerate(['one:10','two:20']):
  print(k)

(0, 'one:10')
(1, 'two:20')


In [ ]:
a = (['one:10','two:20'])
for k,v in enumerate(a):
  print(k, a)

0 ['one:10', 'two:20']
1 ['one:10', 'two:20']


###zip
 - 매개인자로 여러 목록을 받아 각 목록의 요소를 튜플에 담아 목록에 저장한다.

In [ ]:
a = [1,2,3,4,5]
b = ['a','b','c','d','e']

for x in zip(a,b):
  print(x)

(1, 'a')
(2, 'b')
(3, 'c')
(4, 'd')
(5, 'e')


In [ ]:
a = []
for x in range(2,10):
  a.append(x)

print(a)

[2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a = []
for x in range(1,10): # 2
  for y in range(2,10): # 3
    print('{} X {} = {}'.format(y, x, x*y), end= '\t')
  print()

2 X 1 = 2	3 X 1 = 3	4 X 1 = 4	5 X 1 = 5	6 X 1 = 6	7 X 1 = 7	8 X 1 = 8	9 X 1 = 9	
2 X 2 = 4	3 X 2 = 6	4 X 2 = 8	5 X 2 = 10	6 X 2 = 12	7 X 2 = 14	8 X 2 = 16	9 X 2 = 18	
2 X 3 = 6	3 X 3 = 9	4 X 3 = 12	5 X 3 = 15	6 X 3 = 18	7 X 3 = 21	8 X 3 = 24	9 X 3 = 27	
2 X 4 = 8	3 X 4 = 12	4 X 4 = 16	5 X 4 = 20	6 X 4 = 24	7 X 4 = 28	8 X 4 = 32	9 X 4 = 36	
2 X 5 = 10	3 X 5 = 15	4 X 5 = 20	5 X 5 = 25	6 X 5 = 30	7 X 5 = 35	8 X 5 = 40	9 X 5 = 45	
2 X 6 = 12	3 X 6 = 18	4 X 6 = 24	5 X 6 = 30	6 X 6 = 36	7 X 6 = 42	8 X 6 = 48	9 X 6 = 54	
2 X 7 = 14	3 X 7 = 21	4 X 7 = 28	5 X 7 = 35	6 X 7 = 42	7 X 7 = 49	8 X 7 = 56	9 X 7 = 63	
2 X 8 = 16	3 X 8 = 24	4 X 8 = 32	5 X 8 = 40	6 X 8 = 48	7 X 8 = 56	8 X 8 = 64	9 X 8 = 72	
2 X 9 = 18	3 X 9 = 27	4 X 9 = 36	5 X 9 = 45	6 X 9 = 54	7 X 9 = 63	8 X 9 = 72	9 X 9 = 81	


In [ ]:
a = []
for x in range(1,10): # 2
  for y in range(2,10): # 3
    #print('{} X {} = {}'.format(y, x, x*y), end= '\t')
    a.append('{} X {} = {}'.format(x, y, x*y))
    a.append('\t')
  a.append('\n')

print(a)

['1 X 2 = 2', '\t', '1 X 3 = 3', '\t', '1 X 4 = 4', '\t', '1 X 5 = 5', '\t', '1 X 6 = 6', '\t', '1 X 7 = 7', '\t', '1 X 8 = 8', '\t', '1 X 9 = 9', '\t', '\n', '2 X 2 = 4', '\t', '2 X 3 = 6', '\t', '2 X 4 = 8', '\t', '2 X 5 = 10', '\t', '2 X 6 = 12', '\t', '2 X 7 = 14', '\t', '2 X 8 = 16', '\t', '2 X 9 = 18', '\t', '\n', '3 X 2 = 6', '\t', '3 X 3 = 9', '\t', '3 X 4 = 12', '\t', '3 X 5 = 15', '\t', '3 X 6 = 18', '\t', '3 X 7 = 21', '\t', '3 X 8 = 24', '\t', '3 X 9 = 27', '\t', '\n', '4 X 2 = 8', '\t', '4 X 3 = 12', '\t', '4 X 4 = 16', '\t', '4 X 5 = 20', '\t', '4 X 6 = 24', '\t', '4 X 7 = 28', '\t', '4 X 8 = 32', '\t', '4 X 9 = 36', '\t', '\n', '5 X 2 = 10', '\t', '5 X 3 = 15', '\t', '5 X 4 = 20', '\t', '5 X 5 = 25', '\t', '5 X 6 = 30', '\t', '5 X 7 = 35', '\t', '5 X 8 = 40', '\t', '5 X 9 = 45', '\t', '\n', '6 X 2 = 12', '\t', '6 X 3 = 18', '\t', '6 X 4 = 24', '\t', '6 X 5 = 30', '\t', '6 X 6 = 36', '\t', '6 X 7 = 42', '\t', '6 X 8 = 48', '\t', '6 X 9 = 54', '\t', '\n', '7 X 2 = 14', '\t

##compression
 - compression이란 iterable한 오브젝트를 생성하기 위한 방법 중 하나이다.
   - List Compression(LC)
   - Set compression(SC)
   - Dict Compression(DC)

### List Compression
 - List 정의시 값을 정하지 않고 호출시 리스트 내의 값들이 처리되도록 구성
 - A =[표현식 for in 반복가능객체(interable)]
 - A =[표현식 for in 반복가능객체(interable) if 논리식]
 - A =[표현식 for in 반복가능객체(interable)1 for 항목2 in 반복가능객체(interable)2 if 논리식]

In [ ]:
s = []
for x in range(10):
  s.append(x**2)
print(s)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
s = [x**2 for x in range(10)]
print(s)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
s = []
for x in range(10):
 if x % 2 == 0:
  s.append(x**2)
print(s)

[0, 4, 16, 36, 64]


In [ ]:
s = [x**2 for x in range(10) if x % 2 == 0]
print(s)

[0, 4, 16, 36, 64]


In [ ]:
s = []
for i in range(1,3):
  for j in range(4,8):
    print('{}{}'.format(i,j))
    s.append((i,j))
print(s)

14
15
16
17
24
25
26
27
[(1, 4), (1, 5), (1, 6), (1, 7), (2, 4), (2, 5), (2, 6), (2, 7)]


In [ ]:
s = [ (i,j) for i in range(1,3) for j in range(4,8) ]
print(s)

[(1, 4), (1, 5), (1, 6), (1, 7), (2, 4), (2, 5), (2, 6), (2, 7)]


##총판금액을 구하는 프로그램(list comrehension 사용)
cnt=[1,1,2,1]

prod=[500,1000,400,600]

In [ ]:
del sum
del print

NameError: ignored

In [ ]:
s = []
cnt=[1,1,2,1]
prod=[500,1000,400,600]
for i,j in zip(cnt, prod):
  s.append(i*j)

print(sum(s))

2900


In [ ]:
cnt=[1,1,2,1]
prod=[500,1000,400,600]
s = sum([i*j  for i,j in zip(cnt, prod) ])
print(s)

2900


'e'가 포함되어 있는 과일들만 추출해서 대문자로 출력하는 프로그램을 구현하세요.

fruits = ['apple', 'banana', 'cherry', 'grape', 'kiwi', 'tomato']

[출력결과]
['APPLE', 'CHERRY', 'GRAPE']

In [ ]:
fruits = ['apple', 'banana', 'cherry', 'grape', 'kiwi', 'tomato']
s = ([ item.upper() for item in fruits if 'e' in item ])
print(s)


['APPLE', 'CHERRY', 'GRAPE']


제어문이나 comprehension을 이용한 문제풀이

[문제1]  
리스트에 저장된 문자열 중에서 길이가 5인 것들만 리스트 형태로 출력하도록 구현하세요.  

a= ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']  

[출력결과]     
['alpha', 'bravo', 'delta', 'hotel', 'india']

In [ ]:
a = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']
b = [g for g in a if len(g) ==5]

b

['alpha', 'bravo', 'delta', 'hotel', 'india']

[문제2]    
가로 크기를 저장한 리스트를 활용해서 가로 크기가 불규칙한  리스트를 생성하도록 프로그램을 구현하세요.

a = [3, 1,3, 2, 5]  


[출력결과]  
[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


In [ ]:
a = [3, 1,3, 2, 5]
b = [[0]*g for g in a]
b

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]

[문제3]    
포트폴리오의 총 비용을 계산하는 프로그램을 구현하세요.   

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]     

[출력결과]  
44671.15

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
cost = sum([g['shares'] * g['price'] for g in portfolio])
cost

44671.15

[문제4]  
포트폴리오에서 100주 이상 보유한 종목의 리스트를 출력하는 프로그램을 구현하세요.    
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  


[출력결과]    
[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]


In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
list = [g for g in portfolio if g['shares'] >= 100]
list


[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]

[문제5]

보유한 MSFT와 IBM주식 전체 리스트를 출력하는 프로그램을 구현하세요.  

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  

[출력결과]   
[{'name': 'IBM', 'price': 91.1, 'shares': 50},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200},
 {'name': 'MSFT', 'price': 65.1, 'shares': 50},
 {'name': 'IBM', 'price': 70.44, 'shares': 100}]  



In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
list = [ s for s in portfolio if s['name'] in {'MSFT','IBM'} ]
list

[문제6]
보유 종목 중 가격이 10,000달러가 넘는 것의 리스트를 구현하는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]    
[{'name': 'CAT', 'price': 83.44, 'shares': 150},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200}]

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
list = [g for g in portfolio if g['shares'] * g['price'] > 10000]
list

[{'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23}]

[문제7]   
portfolio에서 얻은 name과 shares를 가지고 튜플의 리스트 (name, shares)를 만드는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]   
[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]


In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
haha = [(g['name'],g['shares']) for g in portfolio]
haha

[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]

[문제8]  

리스트에서 int만 추출하는 프로그램을 구현하세요.  
oldlist = [1, 2, 'A', False, 3]

[출력결과]   
[1, 2, 3]  


In [ ]:
oldlist = [1, 2, 'A', False, 3]
hu = [g for g in oldlist if type(g)==int]
hu

[1, 2, 3]

[문제9]   
1부터 10까지의 홀수, 짝수로 출력하는 프로그램을 구현하세요.

[출력결과]   
{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}

In [ ]:
result = {g:'짝수' if g%2==0 else '홀수' for g in range(1, 11)}
result

{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}

###dict comprehension
 - 사전 정의시 값을 정하지 않고 호출시 사전 내의 값들이 처리되도록 구성
 - A ={표현식 for(k,v) in 반복가능객체 if 논리식)

In [ ]:
d = {}
for k, v in zip(range(9), range(9)):
  d[k]=v
print(d)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}


In [ ]:
d = {k:v for k, v in zip(range(9), range(9))}
print(d)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}


In [ ]:
a = {'x':1, 'y':2, 'z':3}
b = {'w':10, 'x':11, 'y':2}
print(a.keys())
print(b.keys())
c = a.keys() - b.keys()
print(c)
print(type(c))
d = c.pop();
print('{}:{}'.format(d, a[d]))#pop: 완전히 꺼내오는 것.?

dict_keys(['x', 'y', 'z'])
dict_keys(['w', 'x', 'y'])
{'z'}
<class 'set'>
z:3


In [ ]:
a = {'x':1, 'y':2, 'z':3}
b = {'w':10, 'x':11, 'y':2}
k = {key:a[key] for key in a.keys() - b.keys()}
print(k)

{'z': 3}


###set comprehension
 - Set 정의시 값을 정하지 않고 호출시 Set내의 값들이 처리되도록 구성
 - A = {표현식 for 항목 in 반복가능객체 if 논리식}

In [ ]:
k = {(i,j) for i in range(1,3) for j in range(4,8)}
print(k)

{(2, 4), (2, 7), (1, 5), (1, 4), (1, 7), (2, 6), (1, 6), (2, 5)}


## callable
 - 이름 뒤에 ( )를 붙이는 것을 call(호출)이라고 한다.
 - 이름 뒤에 ( )를 붙일 수 있는 것을 callable이라고 한다.
 - python에서 callable인 것은 3가지 유형이 있다.
   - (1)funtion
   - (2)class(init가 정의되었을 경우)
   - (3)object(call이 정의되었을 경우)

In [ ]:
k = 1
k()

TypeError: ignored

In [ ]:
#callable은 built -in함수로 ( )을 붙여 사용할 수 있는지를 True/false로 알려준다.
callable(k)

False

In [ ]:
def prn():
  return 1

In [ ]:
prn()

1

In [ ]:
callable(prn)

True

In [ ]:
#파라미터(인자)와 리턴값이 있는 함수 정의
def max(x, y):
   if x >= y:
      res = x
   else :
      res = y
   return res

In [ ]:
def max(x, y):
   if x >= y:
      return x
   else :
      return y


In [ ]:
max(10, 5)

10

In [ ]:
#파라미터(인자)와 리턴값이 없는 함수 정의
def max(x, y):
   if x >= y:
      print(x)
   else :
      print(y)


In [ ]:
print(max(10, 5))

10
None


In [ ]:
def max( ):
  x = 10
  y = 5
  if x>= y
     print(x)
  else :
     print(y)

SyntaxError: ignored

In [ ]:
print(max())

TypeError: ignored

In [ ]:
#파라미터(인자)가 없고 리턴값이 없는 함수 정의
def max( ):
  x = 10
  y = 5
  if x >= y:
     return x
  else :
     return y

In [ ]:
print(max())

10


##parameter와 argument
1. positional
2. keyword
3. positional & keyword
4. positional only
5. keyword only
6. 가변 positional
7. 가변 keyword

1. positional
 - 함수 호출 : 선언할 때 파라미터의 순서와 호출할 때 argument의 입력순서를 그대로 매칭한다.

In [ ]:
def proc(a, b):
  return (a,b)

In [ ]:
proc(2,4)

(2, 4)

2. keyword
 - keyword 방식을 이용하면 순서와 상관없이 parameter 이름에 따라 값이 대입된다.

In [ ]:
proc(b=4, a=2)

(2, 4)

3. keyword & positional 혼합

In [ ]:
def porc(a, b, c):
  return a, b, c

In [ ]:
#한번 keyword 방식을 사용하면 , 그 다음부터는 keyword 방법만 사용할 수 있다.
proc(c=5, 2, b=3)

SyntaxError: ignored

In [ ]:
#파이썬 버젼 확인
!python --version


Python 3.10.12


4. position only
 - positional only는 함수를 사용할 때 positional방식으로만 parameter를 쓸 수 있도록 강제하는 방법이다.
 - /의 앞에 오는 parameter들은 positional방식으로 입력할 수 있지만, keyword방식으로 입력할 수 없다.
 - positional only 함수를정의할 수 있는 것은 python 3.8부터 지원한다. 이전 버젼에서는 사전 정의된 positional only 함수는 있지만, 사용자가 만들 수는 없었다.

In [ ]:
def proc(a, b, c, /):
  return a, b, c

In [ ]:
proc(4, 5, 6)

(4, 5, 6)

In [ ]:
proc(4, c=6, b=5)

TypeError: ignored

In [ ]:
def proc(a, b, /, c, d):
  return a,b,c,d

In [ ]:
proc(4, 5, 6, 7)

(4, 5, 6, 7)

In [ ]:
proc(4, 5, d=7, c=6)

(4, 5, 6, 7)

5. keyword only
 - keyword only방식은 keyword로만 입력하도록 강제하는 방법이다.
 - '*'이후로는 keyword방식만 가능하다.

In [ ]:
def proc(*, a, b, c, d):
  return a,b,c,d

In [ ]:
proc(a=3, c=5, b=4, d=6)

(3, 4, 5, 6)

In [ ]:
proc(3, 4, d=6, c=5)

TypeError: ignored

In [ ]:
def proc(a, b, *, c, d):
  return a,b,c,d

In [ ]:
proc(3, 4, d=6, c=5)

(3, 4, 5, 6)

6. 가변 positonal
 - 가변 positional은 parameter 이름에 '*'를 붙인다.
 - positonal방식으로 입력되는 argument의 갯수에 상관없이 모두 받아온다.

In [ ]:
def proc(*a):
  print(type(a))
  return a

In [ ]:
print(proc())

<class 'tuple'>
()


In [ ]:
print(proc(1))

<class 'tuple'>
(1,)


In [ ]:
print(proc(1,2,3))

<class 'tuple'>
(1, 2, 3)


7. 가변 keyword
 - 가변 keyword는 parameter 이름에 '**'를 붙인다.
 - keyword방식으로 입력되는 argument의 개수에 상관없이 모두 받아온다.

In [ ]:
def proc(**a):
  print(type(a))
  return a

In [ ]:
proc(x=2, y=3)

<class 'dict'>


{'x': 2, 'y': 3}

In [ ]:
proc(x=3, y=1, z=[1,2,3])

<class 'dict'>


{'x': 3, 'y': 1, 'z': [1, 2, 3]}

가변 positional / 가변 positional은 한번만 사용할 수 있다.

In [ ]:
def proc(*a, *b):
  return a, b

SyntaxError: ignored

In [ ]:
def proc(**a, **b):
  return a, b

SyntaxError: ignored

In [ ]:
x=3; y=5
result = x + y
print(result)

x=4; y=8
result = x + y
print(result)

x=5; y=6
result = x + y
print(result)

8
12
11


In [ ]:
def plus(x, y):
  result = x + y
  return result

In [ ]:
plus(3,5)

8

In [ ]:
plus(4,8)

12

In [ ]:
plus(5,6)

11

## overloading
 - 함수의 이름은 같은데, parameter 갯수 또는 parameter타입이 달라야 한다.
 - python은 overloading을 지원하지 않는다.

In [ ]:
def add(a):
  return a+1

In [ ]:
add(6)

7

In [ ]:
def add(a, b):
  return a+b

In [ ]:
add(1,2)

3

In [ ]:
add(3)

TypeError: ignored

In [ ]:
sum([1,2,3])

6

In [ ]:
def sum(a, b):
  return a+b

In [ ]:
sum(1,2)

3

In [ ]:
sum([1,2,3])

TypeError: ignored

In [ ]:
del sum

In [ ]:
type(add)

function

In [ ]:
print(dir(add))

['__annotations__', '__builtins__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']


In [ ]:
#__name__은 함수 이름을 알려준다.
add.__name__

'add'

In [ ]:
display = add

In [ ]:
display(2,3)

In [ ]:
type(display)

SyntaxError: ignored

In [ ]:
#함수를 다른 함수에 재할당해도 __name__은 원래 함수명을 알려준다.
display.__name__

'add'

정수 5개의 argument을 받는 exam함수를 정의해서 합계와 평균을 계산하는 프로그램을 구현하세요

In [ ]:
def exam(a, b, c, d, e):
  hap = a+b+c+d+e
  avg = hap / 5
  print('합계:{}'.format(hap))
  print('평균:{}'.format(avg))

In [ ]:
exam(2,3,4,5,6)

합계:20
평균:4.0


str데이터 타입의 argument을 받는 display함수를 정의하고 문자열의 갯수를 리턴하는 프로그램을 구현하세요.

In [ ]:
#찾는 문자가 없을 때: index() 오류발생, find() -1를 리턴
def display(k, i):
  return k.index(i)

In [ ]:
display('apple', 'a')

0

특정년도의 윤년, 평년을 구해서 리턴하는 프로그램을 구현하세요.
윤년이면 true, 평년이면 false로 리턴하는 프로그램을 구현하세요

In [ ]:
def isLeapyear(year):
   if (year % 4 ==0 and year % 100 != 0) or year % 400 == 0 :
     return True
   else:
     return False

In [ ]:
year = 2017
if isLeapyear(year):
  print('{}년도는 {}입니다.'.format(year, '윤년'))
else:
  print('{}년도는 {}입니다.'.format(year, '평년'))

2017년도는 평년입니다.


In [ ]:
def resultyear(b):
  if b :
    print('{}년도는 {}입니다.'.format(year, '윤년'))
  else:
    print('{}년도는 {}입니다.'.format(year, '평년'))

In [ ]:
year = 2016
checkyear = isLeapyear(year)
resultyear(checkyear)

2016년도는 윤년입니다.
